openapi: 3.0.1
info:
  title: Ticket Service API
  version: v1
servers:
- url: http://localhost:8060
paths:
  /api/v1/tickets:
    get:
      tags:
      - Ticket REST API operations
      summary: Get all Tickets
      operationId: listTickets
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          default: 1
      - name: size
        in: query
        schema:
          type: integer
          default: 10
      responses:
        "200":
          description: All Tickets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllTicketsResponse'
    post:
      tags:
      - Ticket REST API operations
      summary: Create new Ticket
      operationId: createTicket
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketRequest'
        required: true
      responses:
        "201":
          description: Created new Ticket
          headers:
            Location:
              description: Path to new Ticket
              style: simple
              schema:
                type: string
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
  /api/v1/tickets/{ticket_uid}:
    get:
      tags:
      - Ticket REST API operations
      summary: Get Ticket by UUID
      operationId: getTicket
      parameters:
      - name: ticket_uid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Ticket for UUID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'
        "404":
          description: Not found Ticket for UUID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
      - Ticket REST API operations
      summary: Remove Ticket by UUID
      operationId: deleteTicket
      parameters:
      - name: ticket_uid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "204":
          description: Ticket for UUID was removed
    patch:
      tags:
      - Ticket REST API operations
      summary: Update Ticket by UUID
      operationId: updateTicket
      parameters:
      - name: ticket_uid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TicketRequest'
        required: true
      responses:
        "200":
          description: Ticket for UUID was updated
        "400":
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        "404":
          description: Not found Ticket for UUID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/tickets/user/{username}:
    get:
      tags:
      - Ticket REST API operations
      summary: Get Tickets by Username
      operationId: getTicketsByUsername
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: integer
          default: 1
      - name: size
        in: query
        schema:
          type: integer
          default: 10
      responses:
        "200":
          description: Tickets for Username
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllTicketsResponse'
  /api/v1/tickets/flights:
    get:
      tags:
      - Ticket REST API operations
      summary: Get Flights from Gateway
      operationId: getFlights
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          default: 1
      - name: size
        in: query
        schema:
          type: integer
          default: 10
      responses:
        "200":
          description: Flights from Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllFlightsResponse'
components:
  schemas:
    ValidationErrorResponse:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          additionalProperties:
            type: string
    TicketRequest:
      required:
      - username
      - flight_number
      - price
      - status
      type: object
      properties:
        username:
          type: string
          maxLength: 80
        flight_number:
          type: string
          maxLength: 20
        price:
          type: integer
        status:
          type: string
          enum: ["PAID", "CANCELED"]
    TicketResponse:
      required:
      - id
      - ticket_uid
      - username
      - flight_number
      - price
      - status
      type: object
      properties:
        id:
          type: integer
          format: int32
        ticket_uid:
          type: string
          format: uuid
        username:
          type: string
          maxLength: 80
        flight_number:
          type: string
          maxLength: 20
        price:
          type: integer
        status:
          type: string
          enum: ["PAID", "CANCELED"]
    AllTicketsResponse:
      type: object
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/TicketResponse'
    AllFlightsResponse:
      type: object
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/FlightResponse'
    FlightResponse:
      type: object
      properties:
        id:
          type: integer
        flight_number:
          type: string
        datetime:
          type: string
        from_airport_id:
          type: integer
        to_airport_id:
          type: integer
        price:
          type: integer
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
